import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  HomeOutline,
  TeamOutline,
  SafetyOutline,
  SafetyCertificateOutline,
  FileTextOutline,
  UserOutline,
  ToolOutline,
  LogoutOutline,
  SettingOutline,
  ApartmentOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  UserAddOutline,
  ClusterOutline,
  DatabaseOutline,
  CloudOutline,
  CloudServerOutline,
  AppstoreOutline,
  EnvironmentOutline,
  WifiOutline,
  UsergroupAddOutline,
  SearchOutline,
  DownloadOutline,
  UploadOutline,
  LaptopOutline,
  GlobalOutline,
  ApiOutline,
  LockOutline,
  // 云主机相关图标
  PlayCircleOutline,
  PauseCircleOutline,
  ReloadOutline,
  PauseOutline,
  EyeOutline,
  DisconnectOutline,
  // CPU 和存储相关图标
  ThunderboltOutline,
  HddOutline,
  DesktopOutline,
  MonitorOutline,
  // 更多 CPU 相关图标
  ExperimentOutline,
  RocketOutline,
  FireOutline,
  BulbOutline,
  // CPU 图标
  CiOutline
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  HomeOutline,
  TeamOutline,
  SafetyOutline,
  SafetyCertificateOutline,
  FileTextOutline,
  UserOutline,
  ToolOutline,
  LogoutOutline,
  SettingOutline,
  ApartmentOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  UserAddOutline,
  ClusterOutline,
  DatabaseOutline,
  CloudOutline,
  CloudServerOutline,
  AppstoreOutline,
  EnvironmentOutline,
  WifiOutline,
  UsergroupAddOutline,
  SearchOutline,
  DownloadOutline,
  UploadOutline,
  LaptopOutline,
  GlobalOutline,
  ApiOutline,
  LockOutline,
  // 云主机相关图标
  PlayCircleOutline,
  PauseCircleOutline,
  ReloadOutline,
  PauseOutline,
  EyeOutline,
  DisconnectOutline,
  // CPU 和存储相关图标
  ThunderboltOutline,
  HddOutline,
  DesktopOutline,
  MonitorOutline,
  // 更多 CPU 相关图标
  ExperimentOutline,
  RocketOutline,
  FireOutline,
  BulbOutline,
  // CPU 图标
  CiOutline
];
